image: mischief/docker-golang
db: orchardup/postgresql
env:
    - DATABASE_URL={{databaseUrl}}
    - DB_BACKEND=sqlite
script:
    - apt-get update -qq
    - apt-get install -y python2.7 python-pip python-psycopg2 libpq-dev python2.7-dev
    - pip install -r requirements.txt
    - pwd
    - python manage.py test