image: mischief/docker-golang
db: orchardup/postgresql
env:
    - AWS_ACCESS_KEY={{awsAccessKey}}
    - AWS_SECRET_KEY={{awsSecretKey}}
    - DATABASE_URL={{databaseUrl}}
    - DB_BACKEND=sqlite
script:
    - apt-get update -qq
    - apt-get install -y python2.7 python-pip python-psycopg2 libpq-dev python2.7-dev
    - pip install -r requirements.txt
    - python manage.py test
    - pwd
deploy:
    bash:
        script:
            - fab staging deploy
